name: Deploy Palhaçada e Gritaria

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject credentials
        run: |
          sed -i "s|__GH_REPO__|${{ secrets.GH_REPO }}|g" index.html
          sed -i "s|__GITHUB_TOKEN__|${{ secrets.DATA_TOKEN }}|g" index.html

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
